name: "PHPStan neon file check"

on: [push, pull_request]

jobs:
    php-cs-fixer:
        name: "Lint neon file"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@1.7.2
              with:
                  php-version: 7.4
                  extensions: mbstring, ctype, iconv
                  tools: composer, composer-prefetcher

            - name: "Check PHP Version"
              run: php -v

            - name: "Check Composer Version"
              run: composer -V

            - name: "List all php extensions with versions"
              run: php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'

            - name: "Install dependencies with composer"
              run: "composer install --no-interaction --no-progress --no-suggest"

            - name: "Check PHPStan configuration"
              run: |
                  ./vendor/bin/phpstan analyse -c ./base_rules.neon ./
